[package]
name = "fmangroove"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.8"
cpal = "0.15.2"
crossterm = "0.27.0"
anyhow = "1.0.75"
